<?php

declare(strict_types=1);

/** Diccionario en inglés. Mismas claves que config/idiomas/es.php. */
return [
    // Navegación / encabezado
    'nav.herramientas'    => 'Tools',
    'nav.mis_auditorias'  => 'My Audits',
    'nav.catalogo'        => 'Catalog',
    'nav.salir'           => 'Log out',
    'nav.ingresar'        => 'Log in',
    'nav.contactar'       => 'Contact',
    'nav.abrir_menu'      => 'Open navigation menu',
    'nav.idioma'          => 'Language',

    // Pie de página
    'pie.navegacion'      => 'Navigation',
    'pie.contacto'        => 'Contact',
    'pie.proyecto'        => 'Academic project — Database Administration.',
    'pie.eslogan_extra'   => "We reduce the operational risk of your organization's critical information.",
    'pie.arquitectura'    => 'MVC architecture in PHP',

    // Botones y palabras comunes
    'comun.guardar'       => 'Save',
    'comun.cancelar'      => 'Cancel',
    'comun.editar'        => 'Edit',
    'comun.eliminar'      => 'Delete',
    'comun.crear'         => 'Create',
    'comun.volver'        => 'Back',
    'comun.si'            => 'Yes',
    'comun.no'            => 'No',
    'comun.no_aplica'     => 'N/A',
    'comun.buscar'        => 'Search',

    // Authentication
    'auth.eyebrow'            => 'ISO/IEC 27002 risk assessment',
    'auth.ingresar_titulo'    => 'Log in',
    'auth.ingresar_texto'     => 'Access for %s auditors.',
    'auth.correo'             => 'Email address',
    'auth.clave'              => 'Password',
    'auth.entrar'             => 'Log in',
    'auth.sin_cuenta'         => "Don't have an account?",
    'auth.registrarse'        => 'Sign up',
    'auth.registrarse_titulo' => 'Create account',
    'auth.registrarse_texto'  => 'The account is created with an auditor profile.',
    'auth.nombre_completo'    => 'Full name',
    'auth.organizacion'       => 'Organization',
    'auth.confirmar_clave'    => 'Repeat password',
    'auth.crear_cuenta'       => 'Create account',
    'auth.ya_tiene_cuenta'    => 'Already have an account?',
    'auth.iniciar_sesion'     => 'Log in',
    'auth.minimo_caracteres'  => 'Minimum %s characters.',

    // Assessment module — dashboard and new audit
    'eval.comparar_historico'  => 'Compare history',
    'eval.nueva_auditoria'     => 'New audit',
    'eval.mis_auditorias'      => 'My audits',
    'eval.sin_auditorias'      => 'No audits yet.',
    'eval.crear_primera'       => 'Create the first one to start assessing the %s controls in the instrument.',
    'eval.col_organizacion'    => 'Organization',
    'eval.col_area'            => 'Area assessed',
    'eval.col_fecha'           => 'Date',
    'eval.col_estado'          => 'Status',
    'eval.col_indice'          => 'Index',
    'eval.finalizada'          => 'Completed',
    'eval.en_progreso'         => 'In progress',
    'eval.sin_calcular'        => 'not calculated',
    'eval.volver_auditorias'   => '← My audits',
    'eval.crear_auditoria'     => 'Create audit',

    // Assessment module — audit detail (mostrar.php)
    'eval.auditoria_n'         => 'Audit %s',
    'eval.entrevistado'        => 'interviewee:',
    'eval.ver_resultados'      => 'View results',
    'eval.finalizar'           => 'Finish',
    'eval.reabrir'             => 'Reopen',
    'eval.aviso_finalizada'    => 'This audit is finished and no longer accepts changes. Reopen it to keep assessing.',
    'eval.avance'              => 'Assessment progress',
    'eval.de_controles'        => 'of',
    'eval.controles_palabra'   => 'controls',
    'eval.editar_encabezado'   => 'Edit header',
    'eval.guardar_encabezado'  => 'Save header',
    'eval.controles_instrumento' => 'Instrument controls',
    'eval.col_codigo'          => 'Code',
    'eval.col_proceso'         => 'Process',
    'eval.col_enunciado'       => 'Statement',
    'eval.col_resp'            => 'Ans.',
    'eval.col_madurez'         => 'Maturity',

    // Assessment module — rate control (control.php)
    'eval.sin_proceso'         => 'No process',
    'eval.pregunta_auditoria'  => 'Audit question',
    'eval.evidencia_esperada'  => 'Expected evidence',
    'eval.respuesta'           => 'Answer',
    'eval.nivel_madurez'       => 'Observed maturity level',
    'eval.sin_calificar'       => '— Not rated —',
    'eval.criterio_comprobacion' => 'Verification criterion',
    'eval.ninguno'             => '— None —',
    'eval.que_compromete'      => 'What is at risk if this control fails?',
    'eval.confidencialidad'    => 'Confidentiality',
    'eval.integridad'          => 'Integrity',
    'eval.disponibilidad'      => 'Availability',
    'eval.impacto'             => 'Impact',
    'eval.probabilidad'        => 'Probability',
    'eval.nivel_riesgo_reg'    => 'Recorded risk level:',
    'eval.promedio_impacto'    => '(average of impact and probability)',
    'eval.hallazgo'            => 'Finding',
    'eval.recomendacion'       => 'Recommendation',
    'eval.guardar'             => 'Save',
    'eval.guardar_siguiente'   => 'Save and next',
    'eval.estado_si'           => 'Yes',
    'eval.estado_no'           => 'No',
    'eval.estado_na'           => 'N/A',
    'eval.criterio_documentado' => 'Documented',
    'eval.criterio_repetible'   => 'Repeatable',
    'eval.criterio_evidencia'   => 'With evidence',

    // Results / report / comparison
    'eval.resultados'           => 'Results',
    'eval.reporte_pdf'          => 'Executive report (PDF)',
    'eval.aviso_riesgo_critico' => 'This audit has at least one dimension (C, I or D) in the red zone. Review the risk exposure before delivering the report.',
    'eval.cumplimiento_general' => 'Overall compliance',
    'eval.madurez_promedio'     => 'Average maturity',
    'eval.indice_general_riesgo' => 'Overall risk index',
    'eval.controles_respondidos' => 'Controls answered:',
    'eval.si_minuscula'         => 'yes',
    'eval.no_minuscula'         => 'no',
    'eval.na_minuscula'         => 'n/a',
    'eval.exposicion_riesgo'    => 'Risk exposure',
    'eval.sin_dimensiones'      => 'No controls with marked dimensions and rated maturity yet.',
    'eval.matriz_riesgo'        => 'Risk matrix',
    'eval.sin_impacto_prob'     => 'No controls with rated impact and probability yet.',
    'eval.eje_matriz'           => 'Probability (vertical axis) × Impact (horizontal axis)',
    'eval.eje_matriz_reporte'   => 'Rows: probability 5→1 · Columns: impact 1→5',
    'eval.cumplimiento_dominio' => 'Compliance by domain',
    'eval.sin_controles_eval'   => 'No controls assessed yet.',
    'eval.col_dominio'          => 'Domain',
    'eval.col_cumplimiento'     => 'Compliance',
    'eval.sin_datos'            => 'no data',
    'eval.menor_madurez'        => 'Controls with lowest maturity',
    'eval.mayor_riesgo'         => 'Controls with highest risk',
    'eval.sin_datos_suficientes' => 'Not enough data.',
    'eval.reporte_ejecutivo'    => 'Executive report',
    'eval.generado_el'          => 'Generated on %s by %s',
    'eval.auditor'               => 'Auditor',
    'eval.admin_entrevistado'    => 'DB administrator interviewed',
    'eval.comparacion_historica' => 'Historical comparison',
    'eval.evolucion_indice'      => 'Trend of the overall risk index by organization.',
    'eval.sin_auditorias_comparar' => 'No audits to compare yet.',
    'eval.solo_una_auditoria'    => 'There is only one audit so far. At least two are needed to see a trend.',
    'eval.riesgo'                 => 'risk',

    // Header form (audit create/edit)
    'eval.admin_entrevistado_label' => 'Database administrator interviewed',
    'eval.seleccione'               => '— Select —',
    'eval.organizacion_registrada'  => 'Their organization is the one recorded as the audited entity.',
    'eval.area_evaluada'            => 'Area assessed',
    'eval.fecha_auditoria'          => 'Audit date',
];
