<?php

declare(strict_types=1);

/**
 * Diccionario en español. Es el idioma por defecto del sitio, así que en
 * rigor casi ninguna vista necesitaría pasar por aquí — pero mantener las
 * mismas claves en los dos archivos es lo que evita que se desincronicen.
 */
return [
    // Navegación / encabezado
    'nav.herramientas'    => 'Herramientas',
    'nav.mis_auditorias'  => 'Mis auditorías',
    'nav.catalogo'        => 'Catálogo',
    'nav.salir'           => 'Salir',
    'nav.ingresar'        => 'Ingresar',
    'nav.contactar'       => 'Contactar',
    'nav.abrir_menu'      => 'Abrir menú de navegación',
    'nav.idioma'          => 'Idioma',

    // Pie de página
    'pie.navegacion'      => 'Navegación',
    'pie.contacto'        => 'Contacto',
    'pie.proyecto'        => 'Proyecto académico — Administración de Bases de Datos.',
    'pie.eslogan_extra'   => 'Reducimos el riesgo operativo de la información crítica de su organización.',
    'pie.arquitectura'    => 'Arquitectura MVC en PHP',

    // Botones y palabras comunes
    'comun.guardar'       => 'Guardar',
    'comun.cancelar'      => 'Cancelar',
    'comun.editar'        => 'Editar',
    'comun.eliminar'      => 'Eliminar',
    'comun.crear'         => 'Crear',
    'comun.volver'        => 'Volver',
    'comun.si'            => 'Sí',
    'comun.no'            => 'No',
    'comun.no_aplica'     => 'No aplica',
    'comun.buscar'        => 'Buscar',

    // Autenticación
    'auth.eyebrow'            => 'Evaluación de riesgo ISO/IEC 27002',
    'auth.ingresar_titulo'    => 'Iniciar sesión',
    'auth.ingresar_texto'     => 'Acceso para auditores de %s.',
    'auth.correo'             => 'Correo electrónico',
    'auth.clave'              => 'Contraseña',
    'auth.entrar'             => 'Entrar',
    'auth.sin_cuenta'         => '¿No tiene cuenta?',
    'auth.registrarse'        => 'Registrarse',
    'auth.registrarse_titulo' => 'Crear cuenta',
    'auth.registrarse_texto'  => 'La cuenta se crea con perfil de auditor.',
    'auth.nombre_completo'    => 'Nombre completo',
    'auth.organizacion'       => 'Organización',
    'auth.confirmar_clave'    => 'Repetir contraseña',
    'auth.crear_cuenta'       => 'Crear cuenta',
    'auth.ya_tiene_cuenta'    => '¿Ya tiene cuenta?',
    'auth.iniciar_sesion'     => 'Iniciar sesión',
    'auth.minimo_caracteres'  => 'Mínimo %s caracteres.',

    // Módulo de evaluación — panel y alta de auditoría
    'eval.comparar_historico'  => 'Comparar histórico',
    'eval.nueva_auditoria'     => 'Nueva auditoría',
    'eval.mis_auditorias'      => 'Mis auditorías',
    'eval.sin_auditorias'      => 'Todavía no hay auditorías.',
    'eval.crear_primera'       => 'Cree la primera para empezar a evaluar los %s controles del instrumento.',
    'eval.col_organizacion'    => 'Organización',
    'eval.col_area'            => 'Área evaluada',
    'eval.col_fecha'           => 'Fecha',
    'eval.col_estado'          => 'Estado',
    'eval.col_indice'          => 'Índice',
    'eval.finalizada'          => 'Finalizada',
    'eval.en_progreso'         => 'En progreso',
    'eval.sin_calcular'        => 'sin calcular',
    'eval.volver_auditorias'   => '← Mis auditorías',
    'eval.crear_auditoria'     => 'Crear auditoría',

    // Módulo de evaluación — detalle de auditoría (mostrar.php)
    'eval.auditoria_n'         => 'Auditoría %s',
    'eval.entrevistado'        => 'entrevistado:',
    'eval.ver_resultados'      => 'Ver resultados',
    'eval.finalizar'           => 'Finalizar',
    'eval.reabrir'             => 'Reabrir',
    'eval.aviso_finalizada'    => 'Esta auditoría está finalizada y no admite cambios. Reábrala para seguir evaluando.',
    'eval.avance'              => 'Avance de la evaluación',
    'eval.de_controles'        => 'de',
    'eval.controles_palabra'   => 'controles',
    'eval.editar_encabezado'   => 'Editar encabezado',
    'eval.guardar_encabezado'  => 'Guardar encabezado',
    'eval.controles_instrumento' => 'Controles del instrumento',
    'eval.col_codigo'          => 'Código',
    'eval.col_proceso'         => 'Proceso',
    'eval.col_enunciado'       => 'Enunciado',
    'eval.col_resp'            => 'Resp.',
    'eval.col_madurez'         => 'Madurez',

    // Módulo de evaluación — calificar control (control.php)
    'eval.sin_proceso'         => 'Sin proceso',
    'eval.pregunta_auditoria'  => 'Pregunta de auditoría',
    'eval.evidencia_esperada'  => 'Evidencia esperada',
    'eval.respuesta'           => 'Respuesta',
    'eval.nivel_madurez'       => 'Nivel de madurez observado',
    'eval.sin_calificar'       => '— Sin calificar —',
    'eval.criterio_comprobacion' => 'Criterio de comprobación',
    'eval.ninguno'             => '— Ninguno —',
    'eval.que_compromete'      => '¿Qué compromete si este control falla?',
    'eval.confidencialidad'    => 'Confidencialidad',
    'eval.integridad'          => 'Integridad',
    'eval.disponibilidad'      => 'Disponibilidad',
    'eval.impacto'             => 'Impacto',
    'eval.probabilidad'        => 'Probabilidad',
    'eval.nivel_riesgo_reg'    => 'Nivel de riesgo registrado:',
    'eval.promedio_impacto'    => '(promedio de impacto y probabilidad)',
    'eval.hallazgo'            => 'Hallazgo',
    'eval.recomendacion'       => 'Recomendación',
    'eval.guardar'             => 'Guardar',
    'eval.guardar_siguiente'   => 'Guardar y siguiente',
    'eval.estado_si'           => 'Sí',
    'eval.estado_no'           => 'No',
    'eval.estado_na'           => 'No aplica',
    'eval.criterio_documentado' => 'Documentado',
    'eval.criterio_repetible'   => 'Repetible',
    'eval.criterio_evidencia'   => 'Con evidencia',

    // Resultados / reporte / comparación
    'eval.resultados'           => 'Resultados',
    'eval.reporte_pdf'          => 'Reporte ejecutivo (PDF)',
    'eval.aviso_riesgo_critico' => 'Esta auditoría tiene al menos una dimensión (C, I o D) en zona roja. Revise la exposición al riesgo antes de entregar el informe.',
    'eval.cumplimiento_general' => 'Cumplimiento general',
    'eval.madurez_promedio'     => 'Madurez promedio',
    'eval.indice_general_riesgo' => 'Índice general de riesgo',
    'eval.controles_respondidos' => 'Controles respondidos:',
    'eval.si_minuscula'         => 'sí',
    'eval.no_minuscula'         => 'no',
    'eval.na_minuscula'         => 'no aplica',
    'eval.exposicion_riesgo'    => 'Exposición al riesgo',
    'eval.sin_dimensiones'      => 'Todavía no hay controles con dimensiones marcadas y madurez calificada.',
    'eval.matriz_riesgo'        => 'Matriz de riesgo',
    'eval.sin_impacto_prob'     => 'Todavía no hay controles con impacto y probabilidad calificados.',
    'eval.eje_matriz'           => 'Probabilidad (eje vertical) × Impacto (eje horizontal)',
    'eval.eje_matriz_reporte'   => 'Filas: probabilidad 5→1 · Columnas: impacto 1→5',
    'eval.cumplimiento_dominio' => 'Cumplimiento por dominio',
    'eval.sin_controles_eval'   => 'Sin controles evaluados todavía.',
    'eval.col_dominio'          => 'Dominio',
    'eval.col_cumplimiento'     => 'Cumplimiento',
    'eval.sin_datos'            => 'sin datos',
    'eval.menor_madurez'        => 'Controles con menor madurez',
    'eval.mayor_riesgo'         => 'Controles con mayor riesgo',
    'eval.sin_datos_suficientes' => 'Sin datos suficientes.',
    'eval.reporte_ejecutivo'    => 'Reporte ejecutivo',
    'eval.generado_el'          => 'Generado el %s por %s',
    'eval.auditor'               => 'Auditor',
    'eval.admin_entrevistado'    => 'Administrador de BD entrevistado',
    'eval.comparacion_historica' => 'Comparación histórica',
    'eval.evolucion_indice'      => 'Evolución del índice general de riesgo por organización.',
    'eval.sin_auditorias_comparar' => 'Todavía no hay auditorías para comparar.',
    'eval.solo_una_auditoria'    => 'Solo hay una auditoría todavía. Se necesitan al menos dos para ver una tendencia.',
    'eval.riesgo'                 => 'riesgo',

    // Formulario de encabezado (alta/edición de auditoría)
    'eval.admin_entrevistado_label' => 'Administrador de base de datos entrevistado',
    'eval.seleccione'               => '— Seleccione —',
    'eval.organizacion_registrada'  => 'Su organización es la que queda registrada como entidad auditada.',
    'eval.area_evaluada'            => 'Área evaluada',
    'eval.fecha_auditoria'          => 'Fecha de la auditoría',
];
