-- ============================================================================
-- EIF402 · Proyecto Integrador — Evaluación de Riesgo ISO/IEC 27002
-- Datos semilla (Oracle 21c+) — Fase 3 (versión final consolidada)
--
-- Dos bloques:
--   1. Catálogo REAL (7 dominios, 25 procesos, 75 controles), extraído
--      directamente de config/instrumento-bd.php.
--   2. Datos de PRUEBA — usuarios (con organización), una auditoría, dos
--      evaluaciones de ejemplo con impacto/probabilidad/nivel_riesgo, y un
--      resultado de riesgo ya calculado con la fórmula confirmada.
--
-- Ejecutar después de 01_esquema_final.sql.
-- ============================================================================

-- ==========================================================================
-- Datos semilla del catálogo real: 7 dominios, 25 procesos, 75 controles
-- Extraído automáticamente de config/instrumento-bd.php (Persona 1)
-- ==========================================================================

-- Dominios (7)
INSERT INTO dominio (clave, nombre, nombre_corto, descripcion) VALUES ('gobierno', 'Gobierno y riesgo', 'Gobierno', 'Quién responde por los datos, cómo se valora el riesgo y con qué competencia y documentación se opera.');
INSERT INTO dominio (clave, nombre, nombre_corto, descripcion) VALUES ('configuracion', 'Configuración y cambios', 'Configuración', 'Instalación asegurada del motor, control de cambios, parches y diseño físico de las bases.');
INSERT INTO dominio (clave, nombre, nombre_corto, descripcion) VALUES ('almacenamiento', 'Memoria y almacenamiento', 'Almacenamiento', 'Memoria, estructuras de almacenamiento, registro de transacciones y proyección de capacidad.');
INSERT INTO dominio (clave, nombre, nombre_corto, descripcion) VALUES ('accesos', 'Accesos y privilegios', 'Accesos', 'Ciclo de vida de las cuentas, roles, accesos privilegiados y autenticación.');
INSERT INTO dominio (clave, nombre, nombre_corto, descripcion) VALUES ('dato', 'Protección del dato', 'Protección', 'Cifrado, enmascaramiento en ambientes no productivos, retención y eliminación segura.');
INSERT INTO dominio (clave, nombre, nombre_corto, descripcion) VALUES ('continuidad', 'Continuidad', 'Continuidad', 'Respaldo, recuperación probada, alta disponibilidad y replicación.');
INSERT INTO dominio (clave, nombre, nombre_corto, descripcion) VALUES ('vigilancia', 'Vigilancia y terceros', 'Vigilancia', 'Monitoreo, auditoría de registros, incidentes y servicios de base de datos contratados o en la nube.');

-- Procesos (25)
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (1, 'gobierno', 'Gobierno y control interno del SGBD', 'ISO/IEC 27001 cl. 5; A.5.1, A.5.2, A.5.3');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (2, 'gobierno', 'Gestión de riesgos inherentes al SGBD', 'ISO/IEC 27005; ISO/IEC 27001 cl. 6.1');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (25, 'gobierno', 'Competencia, documentación e intercambio de información', 'ISO/IEC 27001 cl. 7.2; A.5.37, A.6.3, A.5.14; ISO/IEC 27010');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (3, 'configuracion', 'Instalación y aseguramiento (hardening) del SGBD', 'A.8.9, A.8.19, A.5.21');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (4, 'configuracion', 'Gestión de cambios y de la configuración', 'A.8.32, A.8.31');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (5, 'configuracion', 'Gestión de vulnerabilidades técnicas y parches', 'A.8.8; ISO/IEC 27008');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (6, 'configuracion', 'Creación de bases de datos y diseño físico', 'A.8.27, A.8.9');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (7, 'almacenamiento', 'Administración de memoria y procesos de soporte', 'A.8.6, A.8.16');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (8, 'almacenamiento', 'Gestión de estructuras de almacenamiento', 'A.8.6, A.8.13');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (9, 'almacenamiento', 'Administración del registro de transacciones', 'A.8.13, A.8.15');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (10, 'almacenamiento', 'Gestión de capacidad', 'A.8.6');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (11, 'accesos', 'Gestión de cuentas de usuario', 'A.5.16, A.5.18');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (12, 'accesos', 'Gestión de privilegios y roles', 'A.8.2, A.5.15');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (13, 'accesos', 'Cuentas administrativas y accesos privilegiados', 'A.8.2, A.5.17, A.8.15');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (14, 'accesos', 'Autenticación y política de contraseñas', 'A.5.17, A.8.5, A.8.28');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (15, 'dato', 'Criptografía y gestión de llaves', 'A.8.24, A.8.20');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (16, 'dato', 'Enmascaramiento y ambientes no productivos', 'A.8.11, A.8.33, A.8.31');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (23, 'dato', 'Retención, archivado y eliminación segura', 'A.5.33, A.5.34, A.8.10, A.7.14');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (17, 'continuidad', 'Respaldo de bases de datos', 'A.8.13, A.8.24');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (18, 'continuidad', 'Recuperación y continuidad del servicio', 'A.8.13, A.5.29, A.5.30');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (19, 'continuidad', 'Alta disponibilidad y replicación', 'A.8.14, A.8.16');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (20, 'vigilancia', 'Monitoreo y gestión del desempeño', 'A.8.16, A.8.6; ISO/IEC 27004');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (21, 'vigilancia', 'Auditoría de la base de datos y registros', 'A.8.15, A.8.17; ISO/IEC 27007');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (22, 'vigilancia', 'Gestión de incidentes de seguridad en la base de datos', 'A.5.24 a A.5.28');
INSERT INTO proceso (numero, clave_dominio, nombre, ancla) VALUES (24, 'vigilancia', 'Proveedores y bases de datos gestionadas o en la nube', 'A.5.19 a A.5.23; ISO/IEC 27011');

-- Controles (75)
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-001', 1, 'ISO/IEC 27002:2022 A.5.1', 'Existe una política de seguridad de la información aprobada por la dirección que trata de manera explícita la administración de bases de datos y se revisa al menos una vez al año.', 'Política vigente con firma de aprobación, acta de la dirección y registro de la última revisión.', '¿Quién aprobó la política vigente de seguridad de la información, en qué fecha se revisó por última vez y qué apartados tratan específicamente las bases de datos?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-002', 1, 'ISO/IEC 27002:2022 A.5.2', 'Las responsabilidades de propiedad, custodia y administración de cada base de datos están asignadas nominalmente y documentadas.', 'Matriz de responsabilidades o descripciones de puesto donde consten los nombres y las bases asignadas.', '¿Quién es el propietario y quién el custodio de cada base de datos en producción, y en qué documento consta esa asignación?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-003', 1, 'ISO/IEC 27002:2022 A.5.3', 'Las funciones de desarrollo, administración de la base de datos y revisión de sus registros de auditoría están segregadas entre personas distintas.', 'Organigrama del área y comparación de las cuentas asignadas a cada función.', '¿Cómo se separan las funciones de quien desarrolla, quien administra y quien revisa las bitácoras, y qué control compensatorio aplica cuando una sola persona cubre varias?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-004', 2, 'ISO/IEC 27005:2022 cl. 7.2; A.5.9', 'Existe un inventario actualizado de las bases de datos en operación que registra motor, versión, responsable y clasificación de la información contenida.', 'Inventario con fecha de última actualización y criterio de clasificación aplicado.', '¿Cuántas bases de datos están en operación hoy, cómo se mantiene actualizado ese inventario y quién clasifica la información que contienen?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-005', 2, 'ISO/IEC 27005:2022 cl. 7.3; ISO/IEC 27001 cl. 6.1.2', 'Se ha realizado una evaluación de riesgos de las bases de datos que identifica amenazas, probabilidad e impacto sobre la integridad, la confidencialidad y la disponibilidad.', 'Matriz de riesgos fechada, con la metodología y las escalas de valoración declaradas.', '¿Con qué metodología se evaluaron los riesgos de las bases de datos, cuándo se hizo la última valoración y quiénes participaron en ella?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-006', 2, 'ISO/IEC 27001 cl. 6.1.3 y cl. 8.3', 'Cada riesgo tratado o aceptado cuenta con un plan con responsable asignado, fecha compromiso y seguimiento registrado.', 'Plan de tratamiento con el estado de cada riesgo y acta de aceptación del riesgo residual.', '¿Qué riesgos de base de datos siguen abiertos, quién responde por cada plan de tratamiento y en qué fecha vencen?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-007', 25, 'ISO/IEC 27001 cl. 7.2; A.6.3', 'El personal a cargo de las bases de datos tiene competencias definidas por puesto y evidencia de formación o certificación vigente.', 'Perfil de puesto, plan de capacitación y constancias del último año.', '¿Qué formación específica en el motor y en seguridad de la información recibió el equipo de base de datos en el último año y cómo se acredita?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-008', 25, 'ISO/IEC 27002:2022 A.5.37', 'Los procedimientos operativos de la base de datos están documentados, versionados y disponibles para quien debe ejecutarlos.', 'Repositorio de procedimientos con control de versiones y fecha de última revisión.', '¿Dónde está el procedimiento operativo de la base de datos, qué versión está vigente y cuándo se actualizó por última vez?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-009', 25, 'ISO/IEC 27002:2022 A.5.14; ISO/IEC 27010:2015', 'El intercambio de información de la base de datos con terceros está regulado por acuerdos que definen el medio, el cifrado y las responsabilidades de cada parte.', 'Acuerdos de intercambio firmados y registro de las transferencias realizadas.', '¿Qué información de la base de datos se envía a terceros, por qué medio viaja y qué acuerdo respalda cada intercambio?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-010', 3, 'ISO/IEC 27002:2022 A.8.9', 'Existe una línea base de configuración segura del motor, aprobada formalmente y aplicada a toda instancia nueva.', 'Documento de línea base aprobado y reporte de conformidad de las instancias en operación.', '¿Qué línea base de configuración se aplica al instalar una instancia nueva y quién verifica que quedó conforme a ella?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-011', 3, 'ISO/IEC 27002:2022 A.8.9, A.8.19', 'Las cuentas por omisión, los esquemas de ejemplo y los servicios no requeridos se deshabilitan o eliminan antes de poner la instancia en producción.', 'Lista de verificación del aseguramiento firmada y consulta de cuentas y servicios activos.', '¿Qué cuentas y componentes por omisión se retiraron de la última instancia instalada y cómo se comprobó que ya no están activos?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-012', 3, 'ISO/IEC 27002:2022 A.5.21, A.8.19', 'El software del motor y sus actualizaciones se obtienen de fuentes autorizadas y se verifica su integridad antes de instalarlos, con registro del responsable.', 'Procedimiento de instalación, lista de personal autorizado y bitácora de instalaciones con verificación de firma o suma de comprobación.', '¿De dónde se descarga el instalador del motor, cómo se comprueba su integridad y quién puede ejecutar la instalación en el servidor?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-013', 4, 'ISO/IEC 27002:2022 A.8.32', 'Todo cambio en el esquema o en la configuración de la base de datos se solicita, autoriza y registra antes de aplicarse en producción.', 'Registro de cambios del último trimestre con solicitante, autorizador, fecha y resultado.', '¿Cómo se solicita y se autoriza un cambio en producción, y quién puede aplicarlo fuera de ese flujo cuando hay una urgencia?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-014', 4, 'ISO/IEC 27002:2022 A.8.32', 'Cada cambio cuenta con un plan de reversión documentado y probado antes de su aplicación en producción.', 'Planes de reversión de los últimos cambios y evidencia de su prueba en un ambiente previo.', '¿Cuál fue el último cambio que hubo que revertir, cuánto tardó la reversión y con qué plan se ejecutó?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-015', 4, 'ISO/IEC 27002:2022 A.8.31', 'Los ambientes de desarrollo, pruebas y producción están separados y no comparten instancias, credenciales ni cuentas de servicio.', 'Inventario de instancias por ambiente y comparación de las cuentas existentes entre ellos.', '¿En qué servidores viven desarrollo, pruebas y producción, y qué credenciales o servicios comparten hoy entre sí?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-016', 5, 'ISO/IEC 27002:2022 A.8.8', 'Existe un proceso definido de identificación de vulnerabilidades del motor, con fuente de información suscrita y periodicidad de revisión establecida.', 'Procedimiento, constancia de la suscripción al boletín del fabricante y último reporte de vulnerabilidades.', '¿Por qué medio se entera el equipo de una vulnerabilidad nueva del motor y con qué frecuencia se revisa esa fuente?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-017', 5, 'ISO/IEC 27002:2022 A.8.8', 'Los parches de seguridad se clasifican por criticidad y se aplican dentro de plazos máximos definidos y aprobados.', 'Política de plazos por criticidad y bitácora de parches con fecha de publicación y fecha de aplicación.', '¿Cuál es el plazo máximo comprometido para aplicar un parche crítico y cuánto se tardó realmente con el último que se aplicó?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-018', 5, 'ISO/IEC 27008:2019; A.8.8', 'Se ejecutan revisiones técnicas de cumplimiento sobre la configuración de la base de datos y sus hallazgos se remedian con seguimiento documentado.', 'Último informe de revisión técnica y estado de remediación de cada hallazgo.', '¿Cuándo se hizo la última revisión técnica de la configuración, quién la ejecutó y cuántos hallazgos siguen abiertos hoy?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-019', 6, 'ISO/IEC 27002:2022 A.8.27', 'El diseño físico de cada base de datos sigue principios de arquitectura segura documentados, incluidas la ubicación de los archivos y la separación de datos e índices.', 'Documento de diseño físico aprobado y esquema de distribución de archivos.', '¿Qué criterios de diseño físico se aplicaron a la última base de datos creada y quién los aprobó?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-020', 6, 'ISO/IEC 27002:2022 A.8.27, A.8.9', 'La creación de bases de datos nuevas sigue un procedimiento formal con autorización previa y registro del resultado de la verificación contra la línea base.', 'Solicitudes de creación autorizadas y bitácora de bases creadas en el último año.', '¿Quién autoriza la creación de una base de datos nueva y cómo se registra que quedó conforme a la línea base?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-021', 6, 'ISO/IEC 27002:2022 A.8.9', 'Los parámetros de inicialización de cada instancia están documentados y sus desviaciones respecto a la línea base están justificadas y autorizadas.', 'Exportación de los parámetros vigentes y registro de desviaciones con su justificación.', '¿Qué parámetros de la instancia se apartan de la línea base, quién autorizó cada desviación y por qué razón técnica?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-022', 7, 'ISO/IEC 27002:2022 A.8.6', 'Las áreas de memoria de la instancia están dimensionadas conforme a un criterio documentado que se revisa con periodicidad definida.', 'Documento de dimensionamiento y última revisión con los datos de uso que la sustentan.', '¿Con qué criterio se dimensionó la memoria de la instancia y cuándo se revisó ese cálculo por última vez?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-023', 7, 'ISO/IEC 27002:2022 A.8.16', 'Los procesos de soporte de la instancia están vigilados y su detención inesperada genera una alerta con destinatario definido.', 'Configuración de las alertas y registro de las alertas emitidas en el último trimestre.', '¿Qué ocurre y a quién se avisa cuando se detiene un proceso de soporte de la instancia fuera del horario laboral?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-024', 7, 'ISO/IEC 27002:2022 A.8.6, A.8.16', 'Los indicadores de uso de memoria y de contención se registran y se conservan durante un periodo definido para el análisis de tendencia.', 'Histórico de métricas de memoria de al menos tres meses y política de retención de esas métricas.', '¿Dónde se guardan las métricas de memoria, cuánto tiempo se conservan y quién las revisa?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-025', 8, 'ISO/IEC 27002:2022 A.8.6', 'El crecimiento de los espacios de almacenamiento se monitorea con umbrales definidos que disparan una alerta antes de la saturación.', 'Configuración de los umbrales y registro del último aviso generado con su atención.', '¿A qué porcentaje de ocupación avisa el sistema, a quién le llega ese aviso y cuándo se activó por última vez?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-026', 8, 'ISO/IEC 27002:2022 A.8.6', 'La distribución de los archivos de datos entre los volúmenes está documentada y responde a un criterio explícito de desempeño y aislamiento.', 'Mapa de archivos por volumen y documento con el criterio de asignación.', '¿Cómo están repartidos los archivos de datos entre los volúmenes y qué criterio se siguió para ese reparto?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-027', 8, 'ISO/IEC 27002:2022 A.8.13, A.8.6', 'Existe un procedimiento documentado para ampliar o reorganizar estructuras de almacenamiento sin interrumpir el servicio.', 'Procedimiento vigente y registro de la última ampliación ejecutada con su tiempo de afectación.', '¿Cómo se amplía un espacio de almacenamiento saturado y cuánto tiempo de servicio se perdió la última vez que ocurrió?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-028', 9, 'ISO/IEC 27002:2022 A.8.13', 'El registro de transacciones opera en un modo que permite la recuperación al punto en el tiempo exigido por el RPO comprometido para cada base.', 'Configuración del modo de registro por instancia y tabla de RPO comprometidos.', '¿En qué modo de registro opera cada base de datos y qué punto de recuperación garantiza ese modo?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-029', 9, 'ISO/IEC 27002:2022 A.8.13', 'Los archivos del registro de transacciones se escriben en una ubicación distinta de la de los archivos de datos.', 'Rutas configuradas en la instancia y evidencia de la separación física o lógica de los volúmenes.', '¿Dónde se escriben los archivos de registro y qué se perdería si desapareciera el volumen de los archivos de datos?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-030', 9, 'ISO/IEC 27002:2022 A.8.13, A.8.15', 'La depuración de los registros de transacciones se rige por una política de retención autorizada y solo se ejecuta sobre registros ya respaldados.', 'Política de retención del registro y bitácora de depuraciones con la verificación previa de respaldo.', '¿Cuánto tiempo se conservan los registros de transacciones, quién autoriza su depuración y cómo se comprueba que ya fueron respaldados?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-031', 10, 'ISO/IEC 27002:2022 A.8.6', 'Existe una proyección de capacidad de almacenamiento, memoria y procesamiento con un horizonte de al menos doce meses.', 'Documento de proyección fechado, con los supuestos de crecimiento declarados.', '¿Hasta cuándo alcanza la capacidad actual según la última proyección y en qué supuestos de crecimiento se basa?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-032', 10, 'ISO/IEC 27002:2022 A.8.6', 'Cada umbral de capacidad tiene un responsable asignado y una ruta de escalamiento definida para cuando se supera.', 'Matriz de umbrales con responsables y registro de los escalamientos ocurridos.', '¿Quién recibe la alerta cuando se supera un umbral de capacidad y qué debe hacer en las primeras horas?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-033', 10, 'ISO/IEC 27002:2022 A.8.6', 'Las decisiones de ampliación de capacidad se sustentan en datos históricos de uso y quedan registradas con su autorización.', 'Expediente de la última ampliación con los datos de uso que la justificaron.', '¿Cuál fue la última ampliación de capacidad, qué datos la justificaron y quién la autorizó?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-034', 11, 'ISO/IEC 27002:2022 A.5.16', 'El alta de una cuenta de base de datos requiere una solicitud autorizada por el propietario de la información y queda registrada.', 'Solicitudes de alta autorizadas de los últimos seis meses.', '¿Quién autoriza el alta de una cuenta nueva en la base de datos y dónde queda constancia de esa autorización?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-035', 11, 'ISO/IEC 27002:2022 A.5.16, A.5.18', 'Las cuentas del personal que causa baja o cambia de función se deshabilitan dentro de un plazo máximo definido.', 'Procedimiento de baja, últimas bajas de personal y fecha real de deshabilitación de sus cuentas.', '¿Cuánto tiempo transcurrió entre la última baja de personal y la deshabilitación efectiva de su cuenta en la base de datos?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-036', 11, 'ISO/IEC 27002:2022 A.5.18', 'Se realiza una revisión periódica de las cuentas activas que confirma que cada una sigue siendo necesaria y tiene un dueño identificado.', 'Acta de la última revisión de cuentas con la lista de cuentas revocadas.', '¿Cuándo se revisaron por última vez las cuentas activas de la base de datos y cuántas se dieron de baja como resultado?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-037', 12, 'ISO/IEC 27002:2022 A.5.15, A.8.2', 'Los privilegios se otorgan mediante roles definidos por función y no de manera directa al usuario.', 'Catálogo de roles con sus privilegios y consulta de privilegios otorgados directamente a usuarios.', '¿Qué roles existen, qué privilegios agrupa cada uno y cuántos usuarios tienen privilegios asignados fuera de un rol?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-038', 12, 'ISO/IEC 27002:2022 A.8.2', 'Las cuentas de aplicación operan con el privilegio mínimo necesario y no poseen privilegios de administración del motor.', 'Consulta de los privilegios efectivos de cada cuenta de aplicación.', '¿Con qué cuenta se conecta la aplicación a la base de datos y qué privilegios exactos tiene esa cuenta hoy?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-039', 12, 'ISO/IEC 27002:2022 A.5.15, A.8.2', 'Los cambios de privilegios quedan registrados con solicitante, autorizador y fecha, y se revisan con periodicidad definida.', 'Bitácora de otorgamiento y revocación de privilegios del último año y acta de su revisión.', '¿Cómo se registra el otorgamiento de un privilegio y quién verifica después que ese otorgamiento siga siendo necesario?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-040', 13, 'ISO/IEC 27002:2022 A.8.2, A.5.17', 'Las cuentas administrativas del motor son nominativas o su uso queda trazado hasta una persona identificable.', 'Lista de cuentas administrativas y descripción del mecanismo de trazabilidad de su uso.', '¿Quiénes conocen la contraseña de la cuenta administrativa del motor y cómo se determina quién la usó en una fecha dada?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-041', 13, 'ISO/IEC 27002:2022 A.8.15, A.8.2', 'El uso de privilegios administrativos se registra en una bitácora que el propio administrador no puede alterar ni borrar.', 'Configuración de la auditoría de sesiones privilegiadas y permisos sobre el destino de la bitácora.', '¿Dónde se escribe la bitácora de las sesiones administrativas y qué impide que un administrador la modifique?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-042', 13, 'ISO/IEC 27002:2022 A.8.2', 'El acceso administrativo se concede de forma temporal y acotada a una tarea específica, con revocación verificada al concluirla.', 'Registro de accesos elevados con vigencia declarada y fecha de revocación confirmada.', '¿Cómo se otorga un acceso administrativo temporal, por cuánto tiempo se concede y quién confirma que se revocó?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-043', 14, 'ISO/IEC 27002:2022 A.5.17', 'El perfil de contraseñas del motor impone longitud mínima, complejidad, vigencia y bloqueo por intentos fallidos.', 'Exportación del perfil de contraseñas configurado y cuentas a las que se aplica.', '¿Qué longitud mínima, qué vigencia y cuántos intentos fallidos tiene configurado el perfil de contraseñas del motor?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-044', 14, 'ISO/IEC 27002:2022 A.8.5', 'El acceso administrativo remoto a la base de datos exige autenticación multifactor o un mecanismo de fortaleza equivalente.', 'Configuración del mecanismo de autenticación reforzada y lista de cuentas cubiertas.', '¿Qué segundo factor se solicita para administrar la base de datos desde fuera de la red interna y a qué cuentas cubre?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-045', 14, 'ISO/IEC 27002:2022 A.8.28, A.5.17', 'Las credenciales de conexión no aparecen en texto claro en el código fuente, los archivos de configuración ni las tareas programadas.', 'Revisión de archivos de configuración y de tareas programadas, y descripción del gestor de secretos utilizado.', '¿Dónde está guardada la contraseña con la que la aplicación se conecta a la base de datos y quién puede leerla?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-046', 15, 'ISO/IEC 27002:2022 A.8.24', 'Los datos clasificados como sensibles están cifrados en reposo con un algoritmo y una longitud de llave vigentes.', 'Inventario de objetos cifrados y configuración del algoritmo empleado.', '¿Qué columnas o espacios de datos están cifrados en reposo, con qué algoritmo y desde cuándo?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-047', 15, 'ISO/IEC 27002:2022 A.8.24, A.8.20', 'Las conexiones a la base de datos viajan cifradas en la red, incluidas las de administración y las de respaldo.', 'Configuración del cifrado en tránsito y captura de verificación del canal.', '¿Cómo se verifica que ninguna conexión a la base de datos viaja sin cifrar, incluidas las tareas automáticas nocturnas?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-048', 15, 'ISO/IEC 27002:2022 A.8.24', 'Las llaves criptográficas tienen un ciclo de vida definido con custodio designado, resguardo separado del dato cifrado y periodicidad de rotación.', 'Procedimiento de gestión de llaves y registro de la última rotación ejecutada.', '¿Quién custodia las llaves de cifrado, dónde se resguardan y cuándo se rotaron por última vez?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-049', 16, 'ISO/IEC 27002:2022 A.8.11, A.8.33', 'Los datos productivos que se copian a ambientes de prueba se enmascaran o se sustituyen antes de ponerse a disposición de los usuarios de ese ambiente.', 'Procedimiento de enmascaramiento y muestra del resultado obtenido en el ambiente de prueba.', '¿Qué campos se enmascaran al copiar datos a pruebas, con qué herramienta y quién valida el resultado?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-050', 16, 'ISO/IEC 27002:2022 A.8.33', 'El uso de datos productivos para pruebas requiere autorización del propietario de la información y queda registrado con su vigencia.', 'Autorizaciones de las últimas copias hacia ambientes no productivos.', '¿Quién autorizó la última copia de datos productivos a pruebas y por cuánto tiempo se autorizó conservarla?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-051', 16, 'ISO/IEC 27002:2022 A.8.31, A.8.33', 'Los ambientes no productivos aplican controles de acceso equivalentes a los de producción sobre los datos que conservan.', 'Comparación de cuentas y privilegios entre el ambiente de producción y el de pruebas.', '¿Quién tiene acceso al ambiente de pruebas y en qué se diferencia esa lista de la de acceso a producción?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-052', 23, 'ISO/IEC 27002:2022 A.5.33', 'Existe una política de retención por tipo de dato que define el plazo de conservación y el momento de la eliminación o el archivado.', 'Política de retención autorizada con su tabla de plazos por tipo de registro.', '¿Cuánto tiempo se conserva cada tipo de registro en la base de datos y en qué documento están definidos esos plazos?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-053', 23, 'ISO/IEC 27002:2022 A.5.34', 'Los datos personales contenidos en la base están identificados y su tratamiento cumple los requisitos legales aplicables.', 'Inventario de tablas y columnas con datos personales y aviso de privacidad vinculado.', '¿Qué tablas o columnas contienen datos personales y qué requisito legal aplica a su conservación?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-054', 23, 'ISO/IEC 27002:2022 A.8.10, A.7.14', 'La eliminación de datos y el retiro de medios de almacenamiento se ejecutan por un método que impide su recuperación y dejan constancia registrada.', 'Procedimiento de borrado seguro y constancias de destrucción de los medios retirados.', '¿Con qué método se borran los datos que ya cumplieron su plazo y qué constancia queda de la destrucción de un disco retirado?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-055', 17, 'ISO/IEC 27002:2022 A.8.13', 'Existe una política de respaldo que define alcance, frecuencia, retención, RPO y RTO por base de datos.', 'Política de respaldo autorizada con la tabla de parámetros por base de datos.', '¿Qué RPO y qué RTO están comprometidos para cada base de datos y quién los aprobó?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-056', 17, 'ISO/IEC 27002:2022 A.8.13', 'La ejecución de cada respaldo se verifica de forma automática y las fallas generan una alerta con atención registrada.', 'Bitácora de respaldos del último mes con resultado y evidencia de la atención de las fallas.', '¿Cómo se entera el equipo de que un respaldo falló durante la noche y qué se hizo con la última falla registrada?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-057', 17, 'ISO/IEC 27002:2022 A.8.13, A.8.24', 'Existe al menos una copia de respaldo cifrada y resguardada en una ubicación distinta de la de la base de datos original.', 'Ubicación del resguardo externo, contrato o convenio que lo respalda y configuración de cifrado de los respaldos.', '¿Dónde está físicamente la copia de respaldo más reciente fuera del sitio principal y cómo está protegida?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-058', 18, 'ISO/IEC 27002:2022 A.8.13', 'Se realizan pruebas de restauración completas con periodicidad definida y su resultado queda documentado.', 'Informe de la última prueba de restauración con los tiempos obtenidos y el responsable de la ejecución.', '¿Cuándo fue la última prueba real de restauración y cuál fue el tiempo de recuperación obtenido?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-059', 18, 'ISO/IEC 27002:2022 A.5.29, A.5.30', 'Existe un plan de continuidad para las bases de datos con roles asignados, secuencia de recuperación y criterios de activación.', 'Plan de continuidad vigente y acta del último ejercicio realizado.', '¿Quién decide activar el plan de continuidad, con qué criterio y en qué orden se recuperan las bases de datos?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-060', 18, 'ISO/IEC 27002:2022 A.5.30, A.8.13', 'Los tiempos de recuperación obtenidos en las pruebas se comparan contra el RTO comprometido y las desviaciones generan acciones con seguimiento.', 'Comparativo entre RTO comprometido y RTO real, con las acciones derivadas y su estado.', '¿Qué diferencia hubo entre el RTO comprometido y el tiempo real de la última prueba, y qué se hizo con esa diferencia?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-061', 19, 'ISO/IEC 27002:2022 A.8.14', 'La arquitectura de alta disponibilidad está documentada y su nivel de redundancia corresponde a la criticidad declarada de cada base de datos.', 'Diagrama de arquitectura y matriz que cruza criticidad con nivel de redundancia.', '¿Qué bases operan con redundancia, de qué tipo, y qué criterio definió cuáles la tienen y cuáles no?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-062', 19, 'ISO/IEC 27002:2022 A.8.16, A.8.14', 'El estado y el retraso de la replicación se monitorean con umbrales que generan alerta ante una desincronización.', 'Tablero o configuración de alertas de retraso de replicación y registro del último incidente detectado.', '¿Cuánto retraso de replicación se considera aceptable, quién lo vigila y cuál fue el máximo observado en el último mes?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-063', 19, 'ISO/IEC 27002:2022 A.8.14', 'La conmutación al nodo secundario se prueba con periodicidad definida y su resultado queda documentado.', 'Bitácora de pruebas de conmutación con fecha y tiempo de indisponibilidad observado.', '¿Cuándo se probó por última vez la conmutación al nodo secundario y cuánto tiempo estuvo el servicio fuera?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-064', 20, 'ISO/IEC 27002:2022 A.8.16', 'Existe un monitoreo continuo de la disponibilidad y el desempeño de la base de datos, con alertas configuradas y destinatario definido.', 'Herramienta de monitoreo, catálogo de alertas y cobertura de instancias vigiladas.', '¿Qué herramienta vigila la base de datos, qué alertas tiene configuradas y a cuántas instancias cubre?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-065', 20, 'ISO/IEC 27004:2016; A.8.16', 'Se han definido indicadores de desempeño con meta, responsable y periodicidad de medición, y se reportan a la dirección.', 'Tablero de indicadores con meta, valor actual y último reporte entregado.', '¿Qué indicadores de desempeño se reportan a la dirección, con qué meta y cada cuánto se miden?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-066', 20, 'ISO/IEC 27002:2022 A.8.6, A.8.16', 'Las consultas de mayor consumo se identifican periódicamente y se optimizan con seguimiento de la mejora obtenida.', 'Informe de consultas críticas y comparativo de tiempos antes y después de la optimización.', '¿Cuál fue la última consulta que se optimizó, cuánto tardaba antes y cuánto tarda ahora?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-067', 21, 'ISO/IEC 27002:2022 A.8.15', 'La auditoría del motor está habilitada y registra al menos los accesos a datos sensibles, los cambios de privilegios y los intentos de conexión fallidos.', 'Configuración de la auditoría y muestra de los eventos efectivamente registrados.', '¿Qué eventos quedan registrados hoy por la auditoría del motor y qué eventos se decidió no registrar y por qué?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-068', 21, 'ISO/IEC 27002:2022 A.8.15; ISO/IEC 27007:2020', 'Los registros de auditoría se revisan con periodicidad definida y cada revisión deja constancia escrita con sus hallazgos.', 'Actas de revisión de bitácoras del último semestre con los hallazgos y su seguimiento.', '¿Quién revisa las bitácoras de la base de datos, cada cuánto lo hace y qué encontró en la última revisión?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-069', 21, 'ISO/IEC 27002:2022 A.8.17', 'Los relojes de los servidores de base de datos están sincronizados contra una fuente de tiempo única y verificada.', 'Configuración del servicio de tiempo y verificación del desfase observado.', '¿Contra qué fuente de tiempo se sincronizan los servidores de base de datos y qué desfase máximo se ha observado?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-070', 22, 'ISO/IEC 27002:2022 A.5.24, A.5.26', 'Existe un procedimiento de gestión de incidentes que define roles, clasificación por severidad y tiempos de respuesta para los eventos de base de datos.', 'Procedimiento vigente y matriz de clasificación con los tiempos comprometidos.', '¿Quién coordina la atención de un incidente en la base de datos y qué tiempo de respuesta se compromete según su severidad?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-071', 22, 'ISO/IEC 27002:2022 A.5.25, A.5.26', 'El personal conoce el canal por el que debe reportar un evento sospechoso en la base de datos y los reportes quedan registrados.', 'Constancia de difusión del canal de reporte y bitácora de eventos reportados.', '¿Por qué canal reporta un operador un comportamiento extraño en la base de datos y cuántos reportes se recibieron en el último año?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-072', 22, 'ISO/IEC 27002:2022 A.5.27, A.5.28', 'Los incidentes cierran con análisis de causa raíz, lecciones aprendidas y evidencia preservada bajo cadena de custodia.', 'Expediente del último incidente con la causa raíz determinada y el registro de custodia de la evidencia.', '¿Cuál fue el último incidente de base de datos, qué causa raíz se determinó y cómo se preservó la evidencia?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-073', 24, 'ISO/IEC 27002:2022 A.5.19, A.5.20', 'Los contratos con proveedores de servicios de base de datos incluyen requisitos de seguridad, niveles de servicio y condiciones de terminación.', 'Contrato vigente con su anexo de seguridad y de niveles de servicio.', '¿Qué nivel de servicio y qué obligaciones de seguridad están escritos en el contrato del proveedor de base de datos?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-074', 24, 'ISO/IEC 27002:2022 A.5.22; ISO/IEC 27011:2016', 'El desempeño y el cumplimiento de seguridad del proveedor se supervisan con evidencia periódica y con validación por parte de la organización.', 'Informes de servicio recibidos y minutas de seguimiento del último año.', '¿Con qué frecuencia se revisa el cumplimiento del proveedor, qué evidencia entrega y quién la valida dentro de la organización?');
INSERT INTO control (codigo, numero_proceso, referencia_iso, enunciado, evidencia_esperada, pregunta) VALUES ('C-075', 24, 'ISO/IEC 27002:2022 A.5.23, A.5.21', 'Para los servicios de base de datos en la nube están definidas la matriz de responsabilidad compartida, la ubicación de los datos y el mecanismo de recuperación al terminar el servicio.', 'Matriz de responsabilidad compartida firmada y cláusula contractual de portabilidad o salida.', '¿En qué país residen los datos alojados en la nube, qué tareas de seguridad ejecuta el proveedor y cómo se recuperan los datos si termina el contrato?');

-- ============================================================================
-- Datos de PRUEBA — usuarios (con organización), auditoría y evaluaciones
-- ============================================================================

-- Contraseña de ambos usuarios de prueba: "cambiar123" (hash de ejemplo,
-- NO usar en producción — Persona 3 debe generarlo con password_hash()).
INSERT INTO usuario (nombre, correo, contrasena_hash, rol, organizacion) VALUES
    ('Ana Alfaro', 'ana.alfaro@consultora.example',
     '$2y$10$X8yZ0h1qFh8yYQeQABCDEuQ9m1r8T2p6v3n5j7k9l1M2n3O4p5Q6R', 'AUDITOR',
     'Consultora de Auditoría Ejemplo S.A.');

INSERT INTO usuario (nombre, correo, contrasena_hash, rol, organizacion) VALUES
    ('Luis Rojas', 'luis.rojas@empresa.example',
     '$2y$10$X8yZ0h1qFh8yYQeQABCDEuQ9m1r8T2p6v3n5j7k9l1M2n3O4p5Q6R', 'ADMIN_BD',
     'Cooperativa de Ejemplo R.L.');

-- id_auditor = 1 (Ana), id_administrador_bd = 2 (Luis) -> organización
-- auditada = 'Cooperativa de Ejemplo R.L.' (se lee desde USUARIO, no de
-- una tabla Organización, que no existe en este modelo).
INSERT INTO auditoria (id_auditor, id_administrador_bd,
                        area_evaluada, fecha, estado)
VALUES (1, 2, 'Administración de Bases de Datos', DATE '2026-08-01', 'EN_PROGRESO');

-- Dos evaluaciones de ejemplo sobre controles reales del catálogo, con
-- impacto/probabilidad/nivel_riesgo y sin pregunta personalizada (NULL =
-- se usa la pregunta por defecto del catálogo).
INSERT INTO evaluacion_control
    (id_auditoria, codigo_control, estado, madurez, criterio,
     afecta_confidencialidad, impacto, probabilidad, nivel_riesgo,
     hallazgo, recomendacion)
VALUES
    (1, 'C-001', 'SI', 3, 'DOCUMENTADO', 0, 2, 2, 2.00,
     'Política vigente firmada en 2025, con revisión anual documentada.',
     'Ninguna acción crítica; mantener la revisión anual programada.');

INSERT INTO evaluacion_control
    (id_auditoria, codigo_control, estado, madurez, criterio,
     afecta_confidencialidad, impacto, probabilidad, nivel_riesgo,
     hallazgo, recomendacion)
VALUES
    (1, 'C-046', 'NO', 1, 'EVIDENCIA', 1, 5, 4, 4.50,
     'No existe cifrado en reposo para las columnas con datos personales en producción.',
     'Implementar cifrado transparente (TDE) o cifrado a nivel de columna en el próximo trimestre.');

-- Resultado de riesgo de ejemplo para Confidencialidad, usando la fórmula
-- confirmada: promedio de madurez de los controles que afectan esa
-- dimensión (aquí solo C-046, madurez 1) / 5 = 0.200 -> zona ROJO.
INSERT INTO resultado_riesgo (id_auditoria, tipo_riesgo, promedio_madurez, zona)
VALUES (1, 'CONFIDENCIALIDAD', 0.200, 'ROJO');

COMMIT;
